services:
  app:
    build: .
    ports:
      - "0.0.0.0:1443:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cardiac_crusade
      - POSTGRES_HOST=db
      - ORIGIN=https://www.dotson97.org
      - RP_ID=www.dotson97.org
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cardiac_crusade
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: